#!/usr/bin/env bash

# Verify tree module code generation and generator invariants.
# Run this when editing generate-tree-modules.py or any logic around
# *-tree-src to *-tree.ncl conversion.

set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
generator="${repo_root}/tools/generate-tree-modules.py"
tmpdir="$(mktemp -d)"
trap 'rm -rf "${tmpdir}"' EXIT

python3 "${generator}" --check

fixture_repo="${tmpdir}/fixtures"
mkdir -p "${fixture_repo}/pkg-tree-src/etc" "${fixture_repo}/pkg-tree-src/dev"
touch "${fixture_repo}/pkg-tree-src/dev/.gitkeep"
printf 'hello tree\n' > "${fixture_repo}/pkg-tree-src/etc/hostname"
touch "${fixture_repo}/pkg-tree-src/etc/.gitkeep"
printf '#!/bin/sh\nexit 0\n' > "${fixture_repo}/pkg-tree-src/init"
chmod 0755 "${fixture_repo}/pkg-tree-src/init"
ln -s usr/bin "${fixture_repo}/pkg-tree-src/bin"
ln -s /proc/self/mounts "${fixture_repo}/pkg-tree-src/etc/mtab"
ln -s missing-target "${fixture_repo}/pkg-tree-src/etc/broken"

python3 "${generator}" --repo-root "${fixture_repo}"

generated="${fixture_repo}/pkg-tree.ncl"
test -f "${generated}"
grep -F 'This file is generated by tools/generate-tree-modules.py.' "${generated}" >/dev/null
grep -F 'Do not edit it directly' "${generated}" >/dev/null
grep -F 'path = "etc/hostname"' "${generated}" >/dev/null
grep -F 'path = "init"' "${generated}" >/dev/null
grep -F 'text = import "pkg-tree-src/etc/hostname" as '\''Text,' "${generated}" >/dev/null
grep -F 'text = import "pkg-tree-src/init" as '\''Text,' "${generated}" >/dev/null
grep -F 'executable = true' "${generated}" >/dev/null
grep -F 'type = "dir"' "${generated}" >/dev/null
grep -F 'path = "dev"' "${generated}" >/dev/null
if grep -F '.gitkeep' "${generated}" >/dev/null; then
  echo "expected generator to ignore .gitkeep placeholders" >&2
  exit 1
fi
if grep -F 'hello tree' "${generated}" >/dev/null; then
  echo "expected generator to import file text instead of embedding literals" >&2
  exit 1
fi
grep -F 'type = "symlink"' "${generated}" >/dev/null
grep -F 'path = "bin"' "${generated}" >/dev/null
grep -F 'target = "usr/bin"' "${generated}" >/dev/null
grep -F 'path = "etc/mtab"' "${generated}" >/dev/null
grep -F 'target = "/proc/self/mounts"' "${generated}" >/dev/null
grep -F 'path = "etc/broken"' "${generated}" >/dev/null
grep -F 'target = "missing-target"' "${generated}" >/dev/null
if grep -F 'path = "etc"' "${generated}" >/dev/null; then
  echo "expected directory with real files and .gitkeep not to be treated as empty" >&2
  exit 1
fi

mkdir -p "${fixture_repo}/empty-tree-src"
if python3 "${generator}" --repo-root "${fixture_repo}" >/dev/null 2>&1; then
  echo "expected generator to reject empty tree source" >&2
  exit 1
fi
rm -rf "${fixture_repo}/empty-tree-src"

printf 'bad\0tree' > "${fixture_repo}/bad-tree-src"
if python3 "${generator}" --repo-root "${fixture_repo}" >/dev/null 2>&1; then
  echo "expected generator to reject binary tree source" >&2
  exit 1
fi
rm -f "${fixture_repo}/bad-tree-src"

ln -s missing-target "${fixture_repo}/broken-tree-src"
if python3 "${generator}" --repo-root "${fixture_repo}" >/dev/null 2>&1; then
  echo "expected generator to reject single-file symlink tree source" >&2
  exit 1
fi

echo "tree codegen check passed"
