#!/usr/bin/env bash

# Rebuild the development HostBundle launcher, stage its fs-tree package
# layout, and update the Source path/hash consumed by
# bobr-bundle-launcher.ncl.

set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
recipes_root="$(cd "${script_dir}/.." && pwd)"
workspace_root="$(cd "${recipes_root}/.." && pwd)"
bobr_root="${workspace_root}/bobr"
target_dir="${bobr_root}/target/x86_64-unknown-linux-musl/debug"
launcher="${target_dir}/bobr-bundle-launcher"
source_root="${target_dir}/bobr-bundle-launcher-tree"
metadata="${script_dir}/bobr-bundle-launcher-local.ncl"
fsobj_hash="${bobr_root}/target/debug/fsobj-hash"

(
  cd "${bobr_root}"
  cargo build-bundle-launcher
  cargo build -p fsobj-hash
)

staging="$(mktemp -d "${target_dir}/.bobr-bundle-launcher-tree.XXXXXX")"
metadata_tmp=""
cleanup() {
  if [ -n "${metadata_tmp}" ]; then
    rm -f -- "${metadata_tmp}"
  fi
  if [ -d "${staging}" ]; then
    rm -rf -- "${staging}"
  fi
}
trap cleanup EXIT

install -Dm755 \
  "${launcher}" \
  "${staging}/usr/libexec/bobr-bundle-launcher"

rm -rf -- "${source_root}"
mv -- "${staging}" "${source_root}"
staging=""

source_object_hash="$("${fsobj_hash}" "${source_root}" | tr -d '\r\n')"
if [[ ! "${source_object_hash}" =~ ^[0-9a-f]{64}$ ]]; then
  echo "invalid fsobj-hash output: ${source_object_hash}" >&2
  exit 1
fi
if [[ "${source_root}" =~ [\"\\] ]] || [[ "${source_root}" == *$'\n'* ]]; then
  echo "source path cannot be represented as a Nickel string: ${source_root}" >&2
  exit 1
fi

metadata_tmp="$(mktemp "${script_dir}/.bobr-bundle-launcher-local.ncl.XXXXXX")"
{
  echo "# Generated by update-bobr-bundle-launcher.sh."
  echo "#"
  echo "# The absolute path is intentionally local-development state. It remains a"
  echo "# valid Source declaration on other machines, but can only be materialized"
  echo "# where the staged directory exists with the declared content hash."
  echo "{"
  printf '  source_path = "%s",\n' "${source_root}"
  printf '  source_object_hash = "%s",\n' "${source_object_hash}"
  echo "}"
} >"${metadata_tmp}"
chmod 0644 "${metadata_tmp}"
mv -- "${metadata_tmp}" "${metadata}"
metadata_tmp=""

echo "updated ${metadata}" >&2
