# shellcheck shell=bash
# The profile variables are generated by resolve_profile() before this sourced
# module is called, so static analysis cannot see their assignments.
# shellcheck disable=SC2154

# Internal post-build publication support for `bobr-build.sh`.
#
# This file is sourced after `resolve_profile`. It emits no stdout: the build
# wrapper reserves stdout for Bobr goal hashes, while repository diagnostics
# and the candidate hand-off belong on stderr.

_output_repository_require_file() {
  local description="$1" path="$2"
  [ -f "${path}" ] \
    || die "${description} is not a regular file: ${path}"
}

_output_repository_decimal_lt() {
  local left="$1" right="$2"
  if [ "${#left}" -lt "${#right}" ]; then
    return 0
  fi
  if [ "${#left}" -gt "${#right}" ]; then
    return 1
  fi
  [[ "${left}" < "${right}" ]]
}

_output_repository_parse_status() {
  local input="$1" parsed
  parsed="$(
    printf '%s\n' "${input}" | jq -er '
      def uint: type == "number" and . >= 0 and floor == .;
      if type != "object" then
        error("status is not an object")
      elif .state == "ready" then
        if (.current_slots | uint) and .current_slots >= 1
           and (.active_slot | type == "object")
           and (.active_slot.serial | uint)
           and (.active_slot.content_bytes | uint)
        then
          ["ready", (.current_slots | tostring),
           (.active_slot.content_bytes | tostring)] | join("|")
        else
          error("invalid ready status")
        end
      elif .state == "empty" or .state == "missing" then
        if .current_slots == 0 and .active_slot == null then
          [.state, "0", ""] | join("|")
        else
          error("invalid empty or missing status")
        end
      else
        error("unknown repository state")
      end
    '
  )" || die "bobr-repo returned an invalid status document"

  IFS='|' read -r output_repository_state \
    output_repository_current_slots \
    output_repository_active_content_bytes <<< "${parsed}"
}

_output_repository_parse_prepare_result() {
  local input="$1"
  printf '%s\n' "${input}" | jq -er '
    if type == "object"
       and keys == ["result"]
       and (.result == "candidate" or .result == "unchanged")
    then
      .result
    else
      error("invalid prepare result")
    end
  '
}

run_output_repository_stage() {
  [ "${profile_output_repository_enabled}" = "1" ] || return 0

  require_cmd bobr-repo
  require_cmd jq

  if [ -n "${profile_output_repository_credentials_file}" ]; then
    _output_repository_require_file "AWS credentials file" \
      "${profile_output_repository_credentials_file}"
  fi
  if [ -n "${profile_output_repository_ca_bundle}" ]; then
    _output_repository_require_file "repository CA bundle" \
      "${profile_output_repository_ca_bundle}"
  fi
  [ "${#profile_output_repository_trusted_keys[@]}" -gt 0 ] \
    || die "output repository has no trusted signing keys"
  local trusted_key
  for trusted_key in "${profile_output_repository_trusted_keys[@]}"; do
    _output_repository_require_file "repository trusted key" "${trusted_key}"
  done

  local -a repository_environment=()
  [ -z "${profile_output_repository_endpoint_url}" ] \
    || repository_environment+=(
      "AWS_ENDPOINT_URL_S3=${profile_output_repository_endpoint_url}"
    )
  [ -z "${profile_output_repository_region}" ] \
    || repository_environment+=("AWS_REGION=${profile_output_repository_region}")
  [ -z "${profile_output_repository_credentials_file}" ] \
    || repository_environment+=(
      "AWS_SHARED_CREDENTIALS_FILE=${profile_output_repository_credentials_file}"
    )
  [ -z "${profile_output_repository_credentials_profile}" ] \
    || repository_environment+=(
      "AWS_PROFILE=${profile_output_repository_credentials_profile}"
    )

  local -a common_args=(
    --repository "${profile_output_repository_repository}"
    --master-url "${profile_output_repository_master_url}"
    --cache "${profile_output_repository_cache}"
  )
  for trusted_key in "${profile_output_repository_trusted_keys[@]}"; do
    common_args+=(--trusted-key "${trusted_key}")
  done
  if [ -n "${profile_output_repository_ca_bundle}" ]; then
    common_args+=(--ca-bundle "${profile_output_repository_ca_bundle}")
  fi

  local status_json
  echo "==> inspect output repository ${profile_output_repository_repository}" >&2
  status_json="$(
    env "${repository_environment[@]}" bobr-repo status \
      "${common_args[@]}" --compact --scan-storage
  )" || die "failed to inspect output repository"
  _output_repository_parse_status "${status_json}"

  if [ "${output_repository_state}" = "missing" ]; then
    [ "${profile_output_repository_create_bucket_if_missing}" = "1" ] \
      || die "output repository bucket is missing and create_bucket_if_missing is false"
    local -a init_args=(
      init
      --repository "${profile_output_repository_repository}"
    )
    if [ -n "${profile_output_repository_ca_bundle}" ]; then
      init_args+=(--ca-bundle "${profile_output_repository_ca_bundle}")
    fi
    echo "==> initialize output repository bucket" >&2
    env "${repository_environment[@]}" bobr-repo "${init_args[@]}" >/dev/null \
      || die "failed to initialize output repository bucket"

    status_json="$(
      env "${repository_environment[@]}" bobr-repo status \
        "${common_args[@]}" --compact --scan-storage
    )" || die "failed to inspect initialized output repository"
    _output_repository_parse_status "${status_json}"
    [ "${output_repository_state}" = "empty" ] \
      || die "initialized output repository did not become empty"
  fi

  local action
  case "${output_repository_state}" in
    empty)
      [ -n "${profile_output_repository_data_base_url}" ] \
        || die "an empty output repository requires data_base_url"
      action="append"
      ;;
    ready)
      if _output_repository_decimal_lt \
        "${output_repository_active_content_bytes}" \
        "${profile_output_repository_max_active_content_bytes}"; then
        action="append"
      elif _output_repository_decimal_lt \
        "${output_repository_current_slots}" \
        "${profile_output_repository_max_current_slots}"; then
        action="add-slot"
      else
        action="rotate"
      fi
      ;;
    missing)
      die "output repository bucket is still missing"
      ;;
    *)
      die "unsupported output repository state: ${output_repository_state}"
      ;;
  esac

  local -a prepare_args=(
    prepare
    --store "${profile_store}"
    --repository "${profile_output_repository_repository}"
    --master-url "${profile_output_repository_master_url}"
    --cache "${profile_output_repository_cache}"
    --output "${profile_output_repository_candidate}"
  )
  for trusted_key in "${profile_output_repository_trusted_keys[@]}"; do
    prepare_args+=(--trusted-key "${trusted_key}")
  done
  if [ -n "${profile_output_repository_ca_bundle}" ]; then
    prepare_args+=(--ca-bundle "${profile_output_repository_ca_bundle}")
  fi
  if [ -n "${profile_output_repository_data_base_url}" ]; then
    prepare_args+=(--data-base-url "${profile_output_repository_data_base_url}")
  fi
  case "${action}" in
    append)
      prepare_args+=(--append --retention "${profile_output_repository_retention}")
      ;;
    add-slot)
      prepare_args+=(--add-slot)
      ;;
    rotate)
      prepare_args+=(--rotate --retention "${profile_output_repository_retention}")
      ;;
  esac

  local prepare_json prepare_result
  echo "==> prepare output repository (${action})" >&2
  prepare_json="$(
    env "${repository_environment[@]}" bobr-repo "${prepare_args[@]}"
  )" || die "failed to prepare output repository"
  prepare_result="$(_output_repository_parse_prepare_result "${prepare_json}")" \
    || die "bobr-repo returned an invalid prepare result"
  case "${prepare_result}" in
    candidate)
      echo "==> output repository candidate: ${profile_output_repository_candidate}" >&2
      echo "    sign and publish it independently with bobr-repo publish" >&2
      ;;
    unchanged)
      echo "==> output repository is unchanged" >&2
      ;;
  esac
}
