#!/usr/bin/env bash

# Regenerate rust-crate-specs.ncl from Mesa's Meson Rust wrap files.

set -euo pipefail

die() {
  echo "update-rust-crate-specs.sh: $*" >&2
  exit 1
}

if [ "$#" -ne 1 ]; then
  echo "usage: $0 MESA-SOURCE-ARCHIVE" >&2
  exit 2
fi

archive="$1"
[ -f "${archive}" ] || die "archive is not a regular file: ${archive}"

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
output="${script_dir}/rust-crate-specs.ncl"
tmpdir="$(mktemp -d)"
trap 'rm -rf "${tmpdir}"' EXIT

wraps="${tmpdir}/wraps"
records="${tmpdir}/records"
generated="${tmpdir}/rust-crate-specs.ncl"
extracted="${tmpdir}/extracted"

tar -tf "${archive}" |
  LC_ALL=C sort |
  awk '/(^|\/)subprojects\/[^/]+-rs\.wrap$/ { print }' >"${wraps}"

[ -s "${wraps}" ] || die "archive contains no subprojects/*-rs.wrap files"

mkdir "${extracted}"
tar -xf "${archive}" -C "${extracted}" -T "${wraps}"

read_wrap_value() {
  local key="$1" file="$2" values

  mapfile -t values < <(
    sed -n \
      "s/^[[:space:]]*${key}[[:space:]]*=[[:space:]]*\\([^[:space:]]*\\)[[:space:]]*$/\\1/p" \
      "${file}"
  )
  [ "${#values[@]}" -eq 1 ] ||
    die "expected exactly one ${key} in ${file}"
  printf '%s\n' "${values[0]}"
}

: >"${records}"
while IFS= read -r wrap; do
  wrap_data="${extracted}/${wrap}"

  source_url="$(read_wrap_value source_url "${wrap_data}")"
  source_hash="$(read_wrap_value source_hash "${wrap_data}")"
  source_filename="$(read_wrap_value source_filename "${wrap_data}")"
  directory="$(read_wrap_value directory "${wrap_data}")"

  if [[ "${source_url}" =~ ^https://crates\.io/api/v1/crates/([^/]+)/([^/]+)/download$ ]]; then
    crate_name="${BASH_REMATCH[1]}"
    crate_version="${BASH_REMATCH[2]}"
  else
    die "unsupported Rust wrap source_url in ${wrap}: ${source_url}"
  fi

  [[ "${crate_name}" =~ ^[A-Za-z0-9_-]+$ ]] ||
    die "unsafe crate name in ${wrap}: ${crate_name}"
  [[ "${crate_version}" =~ ^[A-Za-z0-9.+-]+$ ]] ||
    die "unsafe crate version in ${wrap}: ${crate_version}"
  [[ "${source_hash}" =~ ^[0-9a-f]{64}$ ]] ||
    die "invalid source_hash in ${wrap}: ${source_hash}"
  [ "${source_filename}" = "${crate_name}-${crate_version}.tar.gz" ] ||
    die "unexpected source_filename in ${wrap}: ${source_filename}"
  [ "${directory}" = "${crate_name}-${crate_version}" ] ||
    die "unexpected directory in ${wrap}: ${directory}"

  printf '%s\t%s\t%s\n' \
    "${crate_name}" "${crate_version}" "${source_hash}" >>"${records}"
done <"${wraps}"

duplicate="$(
  LC_ALL=C sort "${records}" |
    awk -F '\t' '
      !duplicate && seen[$1 FS $2]++ { duplicate = $1 " " $2 }
      END { if (duplicate) print duplicate }
    '
)"
[ -z "${duplicate}" ] ||
  die "duplicate Rust crate name and version in Mesa wraps: ${duplicate}"

LC_ALL=C sort "${records}" >"${records}.sorted"

{
  echo "# Generated by update-rust-crate-specs.sh from Mesa Meson wraps."
  echo "# Do not edit by hand."
  echo "["
  while IFS=$'\t' read -r crate_name crate_version source_hash; do
    printf '  {\n'
    printf '    name = "%s",\n' "${crate_name}"
    printf '    version = "%s",\n' "${crate_version}"
    printf '    hash = "%s",\n' "${source_hash}"
    printf '  },\n'
  done <"${records}.sorted"
  echo "]"
} >"${generated}"

if [ -f "${output}" ] && cmp -s "${generated}" "${output}"; then
  echo "unchanged: ${output}"
  exit 0
fi

mv "${generated}" "${output}"
echo "updated: ${output}"
